theme: jekyll-theme-midnight
title: Brian's Knowledge Base
description: This repository serves as a place for Brian De Sousa to store his personal notes and documentation on a variety of technical topics.
show_downloads: false